### ISSUE TITLE
ParlAI Help

### ISSUE THREAD

**Issue by HelloIshHere** [DSmmartin/ai-bot-telegram#1]
Sorry for taking your time but would you be willing to explain how to get a response and make separate worlds and various other things with ParlAI. I am currently having having trouble understanding how to do this aspect. Just wondering if you would be willing to explain or direct me to more resources on this topic. Specifically on how to get a response like specifically, if we were to run it in a python file rather than a command line or terminal.
Best Regards Colin

**Comment by DSmmartin** [comment]
I'm working on understand better how parlai framewoek works.
Stay tuned for the repository updates.
Thanks 😄

**Comment by HelloIshHere** [comment]
Oh ok.

**Comment by HelloIshHere** [comment]
So I am jsut wondering do you understand how to do so?
